<?php
require_once ("Player.php");

/*
 * A domain Class Game
 */

class Player {

    public $id;                  // Unique id in DB
    public $gameId;              // Unique id of game in DB
    public $playerId;            // Ordinal from player type
    public $playerName;          // Player name
    public $serverRoll;          // Roll generated by server
    public $clientRoll;          // Roll generated by client
    public $clientRound;         // Round sent from client
    public $gamePos;             // Position/field in game
    public $lastUpdateTime;      // Last timestamp of change
    public $lastReadTime;        // Last timestamp of read or change

    function __construct() {
    }

    public static function withFull($gameId, $playerId, $playerName = "") {
        $instance = new self();
        $instance->gameId = $gameId;
        $instance->playerId = $playerId;
        $instance->playerName = $playerName;
        $instance->serverRoll = -1;
        $instance->clientRoll = -1;
        $instance->clientRound = 0;
        $instance->gamePos = 0;
        $instance->lastUpdateTime = time();
        $instance->lastReadTime = time();

        return $instance;
    }

    public static function withRow( array $row ) {
        $instance = new self();
        $instance->id = $row["ID"];
        $instance->gameId = $row["GAME_ID"];
        $instance->playerId = $row["PLAYER_ID"];
        $instance->playerName = $row["PLAYER_NAME"];
        $instance->serverRoll = $row["SERVER_ROLL"];
        $instance->clientRoll = $row["CLIENT_ROLL"];
        $instance->clientRound = $row["CLIENT_ROUND"];
        $instance->gamePos = $row["GAME_POS"];
        $instance->lastUpdateTime = $row["LAST_UPDATE_TIME"];
        $instance->lastReadTime = $row["LAST_READ_TIME"];

        return $instance;
    }

    public function rollDice($clientRoll, $clientRound) {
        $this->lastUpdateTime = time();
        $this->lastReadTime = time();
        $this->clientRoll = $clientRoll;
        $this->clientRound = $clientRound;
        $this->serverRoll = rand(1, 6);
        $this->gamePos += $this->serverRoll;
    }

    public function markRead() {
        $this->lastReadTime = time();
    }
}

