<?php
require_once ("Player.php");

/*
 * A domain Class Game
 */

class Player
{

    public $id;                  // Unique id in DB
    public $gameId;              // Unique id of game in DB
    public $playerId;            // Ordinal from player type
    public $playerName;          // Player name
    public $serverRoll;          // Roll generated by server
    public $clientRoll;          // Roll generated by client
    public $clientRound;         // Round sent from client
    public $gamePos;             // Position/field in game

    function __construct() {
    }

    public static function withFull($gameId, $playerId, $playerName = "") {
        $instance = new self();
        $instance->gameId = $gameId;
        $instance->playerId = $playerId;
        $instance->playerName = $playerName;
        $instance->serverRoll = -1;
        $instance->clientRoll = -1;
        $instance->clientRound = 0;
        $instance->gamePos = 0;

        return $instance;
    }

    public static function withRow( array $row ) {
        $instance = new self();
        $instance->id = $row["ID"];
        $instance->gameId = $row["GAME_ID"];
        $instance->playerId = $row["PLAYER_ID"];
        $instance->playerName = $row["PLAYER_NAME"];
        $instance->serverRoll = $row["SERVER_ROLL"];
        $instance->clientRoll = $row["CLIENT_ROLL"];
        $instance->clientRound = $row["CLIENT_ROUND"];
        $instance->gamePos = $row["GAME_POS"];

        return $instance;
    }

    /*
     * you should hookup the DAO here
     */
    public function rollDice($id)
    {
        $result = array(
            "id" =>  $id,
            "value" => rand(1, 6)
        );
        return $result;
    }

}

